### ISSUE TITLE
数据集结构中的autodl-tmp/v2i-calib/data/DAIR-V2X/cooperative/calib/lidar_i2v是怎么得到的  How was the dataset structure in the autodl-tmp/v2i-calib/data/DAIR-V2X/cooperative/calib/lidar_i2v obtained?

### ISSUE THREAD

**Issue by Cillian111** [MassimoQu/v2i-calib#1]
In the dataset structure downloaded from the official website, the Cooperative Vehicle Infrastructure/Cooperative folder only contains the label_world folder. How did the Cooperative Vehicle Infrastructure/Cooperative/calib/lidar_i2v folder come about?

我在官网下载的数据集结构中的cooperative-vehicle-infrastructure/cooperative文件夹里面只有label_world文件夹，那个cooperative-vehicle-infrastructure/cooperative/calib/lidar_i2v是怎么得到的呀？

**Comment by MassimoQu** [comment]
详细可见 https://github.com/AIR-THU/DAIR-V2X/blob/main/tools/dataset_converter/calib_i2v.py 。
因为issue没有及时的通知，隔了挺久才回复。如果紧急可以发邮件提醒我一下：）
